PartyMemberFrame1:ClearAllPoints()--小队框架位置和缩放
PartyMemberFrame1:SetScale(1.2)
PartyMemberFrame1:SetPoint("CENTER", UIParent, "CENTER", -550, 200)
PartyMemberFrame2:ClearAllPoints()
PartyMemberFrame2:SetScale(1.2)
PartyMemberFrame2:SetPoint("CENTER", UIParent, "CENTER", -550, 140)
PartyMemberFrame3:ClearAllPoints()
PartyMemberFrame3:SetScale(1.2)
PartyMemberFrame3:SetPoint("CENTER", UIParent, "CENTER", -550, 80)
PartyMemberFrame4:ClearAllPoints()
PartyMemberFrame4:SetScale(1.2)
PartyMemberFrame4:SetPoint("CENTER", UIParent, "CENTER", -550, 20)

PartyMemberFrame1Name:ClearAllPoints()--小队框架玩家名位置和缩放
PartyMemberFrame1Name:SetScale(0.8)
PartyMemberFrame1Name:SetPoint("CENTER", PartyMemberFrame1, "CENTER", 10, 30)
PartyMemberFrame2Name:ClearAllPoints()
PartyMemberFrame2Name:SetScale(0.8)
PartyMemberFrame2Name:SetPoint("CENTER", PartyMemberFrame2, "CENTER", 10, 30)
PartyMemberFrame3Name:ClearAllPoints()
PartyMemberFrame3Name:SetScale(0.8)
PartyMemberFrame3Name:SetPoint("CENTER", PartyMemberFrame3, "CENTER", 10, 30)
PartyMemberFrame4Name:ClearAllPoints()
PartyMemberFrame4Name:SetScale(0.8)
PartyMemberFrame4Name:SetPoint("CENTER", PartyMemberFrame4, "CENTER", 10, 30)
